<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Description>JJMasterData Hangfire backend for import and export jobs.</Description>
    <PackageProjectUrl>https://www.github.com/jjconsulting/jjmasterdata</PackageProjectUrl>
    <PackageTags>hangfire,jjmasterdata</PackageTags>
    <RootNamespace>JJMasterData.Hangfire</RootNamespace>
    <AssemblyName>JJMasterData.Hangfire</AssemblyName>
    <PackageId>JJMasterData.Hangfire</PackageId>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Hangfire.Core" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\MasterData.Commons\MasterData.Commons.csproj" />
  </ItemGroup>
</Project>
