using System;

namespace JJMasterData.Core.UI.Html;

public enum HtmlTag
{
    A,
    B,
    Blockquote,
    Area,
    Br,
    Div,
    Span,
    Label,
    Input,
    Strong,
    Button,
    H1,
    H2,
    H3,
    H4,
    H5,
    H6,
    Small,
    Ul,
    Li,
    TextArea,
    Script,
    Select,
    Option,
    Table,
    Tr,
    Th,
    Td,
    Thead,
    Tbody,
    Hr,
    I,
    Section,
    P,
    Footer,
    Img,
    Center,
    Video,
    Form,
    FieldSet,
    Legend,
    U,
    OptGroup,
    Nav,
    Ol
}

public static class HtmlTagExtensions
{
    public static string GetTagName(this HtmlTag tag)
    {
        return tag switch
        {
            HtmlTag.A => "a",
            HtmlTag.B => "b",
            HtmlTag.Blockquote => "blockquote",
            HtmlTag.Area => "area",
            HtmlTag.Br => "br",
            HtmlTag.Div => "div",
            HtmlTag.Span => "span",
            HtmlTag.Label => "label",
            HtmlTag.Input => "input",
            HtmlTag.Strong => "strong",
            HtmlTag.Button => "button",
            HtmlTag.H1 => "h1",
            HtmlTag.H2 => "h2",
            HtmlTag.H3 => "h3",
            HtmlTag.H4 => "h4",
            HtmlTag.H5 => "h5",
            HtmlTag.H6 => "h6",
            HtmlTag.Small => "small",
            HtmlTag.Ul => "ul",
            HtmlTag.Li => "li",
            HtmlTag.TextArea => "textarea",
            HtmlTag.Script => "script",
            HtmlTag.Select => "select",
            HtmlTag.Option => "option",
            HtmlTag.Table => "table",
            HtmlTag.Tr => "tr",
            HtmlTag.Th => "th",
            HtmlTag.Td => "td",
            HtmlTag.Thead => "thead",
            HtmlTag.Tbody => "tbody",
            HtmlTag.Hr => "hr",
            HtmlTag.I => "i",
            HtmlTag.Section => "section",
            HtmlTag.P => "p",
            HtmlTag.Footer => "footer",
            HtmlTag.Img => "img",
            HtmlTag.Center => "center",
            HtmlTag.Video => "video",
            HtmlTag.Form => "form",
            HtmlTag.FieldSet => "fieldset",
            HtmlTag.Legend => "legend",
            HtmlTag.U => "u",
            HtmlTag.OptGroup => "optgroup",
            HtmlTag.Nav => "nav",
            HtmlTag.Ol => "ol",
            _ => throw new ArgumentOutOfRangeException(nameof(tag), tag, null)
        };
    }
}