using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;

namespace JJMasterData.Core.DataDictionary.Services;

public enum CountryCode
{
    AF = 0,
    AL = 1,
    DZ = 2,
    AS = 3,
    AD = 4,
    AO = 5,
    AI = 6,
    AG = 7,
    AR = 8,
    AM = 9,
    AW = 10,
    AU = 11,
    AT = 12,
    AZ = 13,
    BS = 14,
    BH = 15,
    BD = 16,
    BB = 17,
    BY = 18,
    BE = 19,
    BZ = 20,
    BJ = 21,
    BM = 22,
    BT = 23,
    BA = 24,
    BW = 25,
    BR = 26,
    IO = 27,
    BG = 28,
    BF = 29,
    BI = 30,
    KH = 31,
    CM = 32,
    CA = 33,
    CV = 34,
    KY = 35,
    CF = 36,
    TD = 37,
    CL = 38,
    CN = 39,
    CX = 40,
    CO = 41,
    KM = 42,
    CG = 43,
    CK = 44,
    CR = 45,
    HR = 46,
    CU = 47,
    CY = 48,
    CZ = 49,
    DK = 50,
    DJ = 51,
    DM = 52,
    DO = 53,
    EC = 54,
    EG = 55,
    SV = 56,
    GQ = 57,
    ER = 58,
    EE = 59,
    ET = 60,
    FO = 61,
    FJ = 62,
    FI = 63,
    FR = 64,
    GF = 65,
    PF = 66,
    GA = 67,
    GM = 68,
    GE = 69,
    DE = 70,
    GH = 71,
    GI = 72,
    GR = 73,
    GL = 74,
    GD = 75,
    GP = 76,
    GU = 77,
    GT = 78,
    GN = 79,
    GW = 80,
    GY = 81,
    HT = 82,
    HN = 83,
    HU = 84,
    IS = 85,
    IN = 86,
    ID = 87,
    IQ = 88,
    IE = 89,
    IL = 90,
    IT = 91,
    JM = 92,
    JP = 93,
    JO = 94,
    KZ = 95,
    KE = 96,
    KI = 97,
    KW = 98,
    KG = 99,
    LV = 100,
    LB = 101,
    LS = 102,
    LR = 103,
    LI = 104,
    LT = 105,
    LU = 106,
    MG = 107,
    MW = 108,
    MY = 109,
    MV = 110,
    ML = 111,
    MT = 112,
    MH = 113,
    MQ = 114,
    MR = 115,
    MU = 116,
    YT = 117,
    MX = 118,
    MC = 119,
    MN = 120,
    ME = 121,
    MS = 122,
    MA = 123,
    MM = 124,
    NA = 125,
    NR = 126,
    NP = 127,
    NL = 128,
    AN = 129,
    NC = 130,
    NZ = 131,
    NI = 132,
    NE = 133,
    NG = 134,
    NU = 135,
    MP = 136,
    NO = 137,
    OM = 138,
    PK = 139,
    PW = 140,
    PA = 141,
    PG = 142,
    PY = 143,
    PE = 144,
    PH = 145,
    PL = 146,
    PT = 147,
    PR = 148,
    QA = 149,
    RO = 150,
    RW = 151,
    WS = 152,
    SM = 153,
    SA = 154,
    SN = 155,
    RS = 156,
    SC = 157,
    SL = 158,
    SG = 159,
    SK = 160,
    SI = 161,
    SB = 162,
    ZA = 163,
    GS = 164,
    ES = 165,
    LK = 166,
    SD = 167,
    SR = 168,
    SZ = 169,
    SE = 170,
    CH = 171,
    TJ = 172,
    TH = 173,
    TG = 174,
    TK = 175,
    TO = 176,
    TT = 177,
    TN = 178,
    TR = 179,
    TM = 180,
    TC = 181,
    TV = 182,
    UG = 183,
    UA = 184,
    AE = 185,
    GB = 186,
    US = 187,
    UY = 188,
    UZ = 189,
    VU = 190,
    WF = 191,
    YE = 192,
    ZM = 193,
    ZW = 194,
    AX = 195,
    AQ = 196,
    BO = 197,
    BN = 198,
    CC = 199,
    CD = 200,
    CI = 201,
    FK = 202,
    GG = 203,
    VA = 204,
    HK = 205,
    IR = 206,
    IM = 207,
    JE = 208,
    KP = 209,
    KR = 210,
    LA = 211,
    LY = 212,
    MO = 213,
    MK = 214,
    FM = 215,
    MD = 216,
    MZ = 217,
    PS = 218,
    PN = 219,
    RE = 220,
    RU = 221,
    BL = 222,
    SH = 223,
    KN = 224,
    LC = 225,
    MF = 226,
    PM = 227,
    VC = 228,
    ST = 229,
    SO = 230,
    SJ = 231,
    SY = 232,
    TW = 233,
    TZ = 234,
    TL = 235,
    VE = 236,
    VN = 237,
    VG = 238,
    VI = 239
}

public sealed record CountryInfo(
    CountryCode Id,
    string Code,
    string Name,
    string DialCode
)
{
    public int Index => (int)Id;
}

public static class CountryService
{
    public static readonly IReadOnlyList<CountryInfo> All;
    private static readonly FrozenDictionary<CountryCode, CountryInfo> ByEnum;
    private static readonly FrozenDictionary<string, CountryInfo> ByCode;

    static CountryService()
    {
        var items = new List<CountryInfo>
        {
            new(CountryCode.AF, "AF", "Afghanistan", "+93"),
            new(CountryCode.AL, "AL", "Albania", "+355"),
            new(CountryCode.DZ, "DZ", "Algeria", "+213"),
            new(CountryCode.AS, "AS", "AmericanSamoa", "+1 684"),
            new(CountryCode.AD, "AD", "Andorra", "+376"),
            new(CountryCode.AO, "AO", "Angola", "+244"),
            new(CountryCode.AI, "AI", "Anguilla", "+1 264"),
            new(CountryCode.AG, "AG", "Antigua and Barbuda", "+1268"),
            new(CountryCode.AR, "AR", "Argentina", "+54"),
            new(CountryCode.AM, "AM", "Armenia", "+374"),
            new(CountryCode.AW, "AW", "Aruba", "+297"),
            new(CountryCode.AU, "AU", "Australia", "+61"),
            new(CountryCode.AT, "AT", "Austria", "+43"),
            new(CountryCode.AZ, "AZ", "Azerbaijan", "+994"),
            new(CountryCode.BS, "BS", "Bahamas", "+1 242"),
            new(CountryCode.BH, "BH", "Bahrain", "+973"),
            new(CountryCode.BD, "BD", "Bangladesh", "+880"),
            new(CountryCode.BB, "BB", "Barbados", "+1 246"),
            new(CountryCode.BY, "BY", "Belarus", "+375"),
            new(CountryCode.BE, "BE", "Belgium", "+32"),
            new(CountryCode.BZ, "BZ", "Belize", "+501"),
            new(CountryCode.BJ, "BJ", "Benin", "+229"),
            new(CountryCode.BM, "BM", "Bermuda", "+1 441"),
            new(CountryCode.BT, "BT", "Bhutan", "+975"),
            new(CountryCode.BA, "BA", "Bosnia and Herzegovina", "+387"),
            new(CountryCode.BW, "BW", "Botswana", "+267"),
            new(CountryCode.BR, "BR", "Brazil", "+55"),
            new(CountryCode.IO, "IO", "British Indian Ocean Territory", "+246"),
            new(CountryCode.BG, "BG", "Bulgaria", "+359"),
            new(CountryCode.BF, "BF", "Burkina Faso", "+226"),
            new(CountryCode.BI, "BI", "Burundi", "+257"),
            new(CountryCode.KH, "KH", "Cambodia", "+855"),
            new(CountryCode.CM, "CM", "Cameroon", "+237"),
            new(CountryCode.CA, "CA", "Canada", "+1"),
            new(CountryCode.CV, "CV", "Cape Verde", "+238"),
            new(CountryCode.KY, "KY", "Cayman Islands", "+ 345"),
            new(CountryCode.CF, "CF", "Central African Republic", "+236"),
            new(CountryCode.TD, "TD", "Chad", "+235"),
            new(CountryCode.CL, "CL", "Chile", "+56"),
            new(CountryCode.CN, "CN", "China", "+86"),
            new(CountryCode.CX, "CX", "Christmas Island", "+61"),
            new(CountryCode.CO, "CO", "Colombia", "+57"),
            new(CountryCode.KM, "KM", "Comoros", "+269"),
            new(CountryCode.CG, "CG", "Congo", "+242"),
            new(CountryCode.CK, "CK", "Cook Islands", "+682"),
            new(CountryCode.CR, "CR", "Costa Rica", "+506"),
            new(CountryCode.HR, "HR", "Croatia", "+385"),
            new(CountryCode.CU, "CU", "Cuba", "+53"),
            new(CountryCode.CY, "CY", "Cyprus", "+537"),
            new(CountryCode.CZ, "CZ", "Czech Republic", "+420"),
            new(CountryCode.DK, "DK", "Denmark", "+45"),
            new(CountryCode.DJ, "DJ", "Djibouti", "+253"),
            new(CountryCode.DM, "DM", "Dominica", "+1 767"),
            new(CountryCode.DO, "DO", "Dominican Republic", "+1 849"),
            new(CountryCode.EC, "EC", "Ecuador", "+593"),
            new(CountryCode.EG, "EG", "Egypt", "+20"),
            new(CountryCode.SV, "SV", "El Salvador", "+503"),
            new(CountryCode.GQ, "GQ", "Equatorial Guinea", "+240"),
            new(CountryCode.ER, "ER", "Eritrea", "+291"),
            new(CountryCode.EE, "EE", "Estonia", "+372"),
            new(CountryCode.ET, "ET", "Ethiopia", "+251"),
            new(CountryCode.FO, "FO", "Faroe Islands", "+298"),
            new(CountryCode.FJ, "FJ", "Fiji", "+679"),
            new(CountryCode.FI, "FI", "Finland", "+358"),
            new(CountryCode.FR, "FR", "France", "+33"),
            new(CountryCode.GF, "GF", "French Guiana", "+594"),
            new(CountryCode.PF, "PF", "French Polynesia", "+689"),
            new(CountryCode.GA, "GA", "Gabon", "+241"),
            new(CountryCode.GM, "GM", "Gambia", "+220"),
            new(CountryCode.GE, "GE", "Georgia", "+995"),
            new(CountryCode.DE, "DE", "Germany", "+49"),
            new(CountryCode.GH, "GH", "Ghana", "+233"),
            new(CountryCode.GI, "GI", "Gibraltar", "+350"),
            new(CountryCode.GR, "GR", "Greece", "+30"),
            new(CountryCode.GL, "GL", "Greenland", "+299"),
            new(CountryCode.GD, "GD", "Grenada", "+1 473"),
            new(CountryCode.GP, "GP", "Guadeloupe", "+590"),
            new(CountryCode.GU, "GU", "Guam", "+1 671"),
            new(CountryCode.GT, "GT", "Guatemala", "+502"),
            new(CountryCode.GN, "GN", "Guinea", "+224"),
            new(CountryCode.GW, "GW", "Guinea-Bissau", "+245"),
            new(CountryCode.GY, "GY", "Guyana", "+595"),
            new(CountryCode.HT, "HT", "Haiti", "+509"),
            new(CountryCode.HN, "HN", "Honduras", "+504"),
            new(CountryCode.HU, "HU", "Hungary", "+36"),
            new(CountryCode.IS, "IS", "Iceland", "+354"),
            new(CountryCode.IN, "IN", "India", "+91"),
            new(CountryCode.ID, "ID", "Indonesia", "+62"),
            new(CountryCode.IQ, "IQ", "Iraq", "+964"),
            new(CountryCode.IE, "IE", "Ireland", "+353"),
            new(CountryCode.IL, "IL", "Israel", "+972"),
            new(CountryCode.IT, "IT", "Italy", "+39"),
            new(CountryCode.JM, "JM", "Jamaica", "+1 876"),
            new(CountryCode.JP, "JP", "Japan", "+81"),
            new(CountryCode.JO, "JO", "Jordan", "+962"),
            new(CountryCode.KZ, "KZ", "Kazakhstan", "+7 7"),
            new(CountryCode.KE, "KE", "Kenya", "+254"),
            new(CountryCode.KI, "KI", "Kiribati", "+686"),
            new(CountryCode.KW, "KW", "Kuwait", "+965"),
            new(CountryCode.KG, "KG", "Kyrgyzstan", "+996"),
            new(CountryCode.LV, "LV", "Latvia", "+371"),
            new(CountryCode.LB, "LB", "Lebanon", "+961"),
            new(CountryCode.LS, "LS", "Lesotho", "+266"),
            new(CountryCode.LR, "LR", "Liberia", "+231"),
            new(CountryCode.LI, "LI", "Liechtenstein", "+423"),
            new(CountryCode.LT, "LT", "Lithuania", "+370"),
            new(CountryCode.LU, "LU", "Luxembourg", "+352"),
            new(CountryCode.MG, "MG", "Madagascar", "+261"),
            new(CountryCode.MW, "MW", "Malawi", "+265"),
            new(CountryCode.MY, "MY", "Malaysia", "+60"),
            new(CountryCode.MV, "MV", "Maldives", "+960"),
            new(CountryCode.ML, "ML", "Mali", "+223"),
            new(CountryCode.MT, "MT", "Malta", "+356"),
            new(CountryCode.MH, "MH", "Marshall Islands", "+692"),
            new(CountryCode.MQ, "MQ", "Martinique", "+596"),
            new(CountryCode.MR, "MR", "Mauritania", "+222"),
            new(CountryCode.MU, "MU", "Mauritius", "+230"),
            new(CountryCode.YT, "YT", "Mayotte", "+262"),
            new(CountryCode.MX, "MX", "Mexico", "+52"),
            new(CountryCode.MC, "MC", "Monaco", "+377"),
            new(CountryCode.MN, "MN", "Mongolia", "+976"),
            new(CountryCode.ME, "ME", "Montenegro", "+382"),
            new(CountryCode.MS, "MS", "Montserrat", "+1664"),
            new(CountryCode.MA, "MA", "Morocco", "+212"),
            new(CountryCode.MM, "MM", "Myanmar", "+95"),
            new(CountryCode.NA, "NA", "Namibia", "+264"),
            new(CountryCode.NR, "NR", "Nauru", "+674"),
            new(CountryCode.NP, "NP", "Nepal", "+977"),
            new(CountryCode.NL, "NL", "Netherlands", "+31"),
            new(CountryCode.AN, "AN", "Netherlands Antilles", "+599"),
            new(CountryCode.NC, "NC", "New Caledonia", "+687"),
            new(CountryCode.NZ, "NZ", "New Zealand", "+64"),
            new(CountryCode.NI, "NI", "Nicaragua", "+505"),
            new(CountryCode.NE, "NE", "Niger", "+227"),
            new(CountryCode.NG, "NG", "Nigeria", "+234"),
            new(CountryCode.NU, "NU", "Niue", "+683"),
            new(CountryCode.MP, "MP", "Northern Mariana Islands", "+1 670"),
            new(CountryCode.NO, "NO", "Norway", "+47"),
            new(CountryCode.OM, "OM", "Oman", "+968"),
            new(CountryCode.PK, "PK", "Pakistan", "+92"),
            new(CountryCode.PW, "PW", "Palau", "+680"),
            new(CountryCode.PA, "PA", "Panama", "+507"),
            new(CountryCode.PG, "PG", "Papua New Guinea", "+675"),
            new(CountryCode.PY, "PY", "Paraguay", "+595"),
            new(CountryCode.PE, "PE", "Peru", "+51"),
            new(CountryCode.PH, "PH", "Philippines", "+63"),
            new(CountryCode.PL, "PL", "Poland", "+48"),
            new(CountryCode.PT, "PT", "Portugal", "+351"),
            new(CountryCode.PR, "PR", "Puerto Rico", "+1 939"),
            new(CountryCode.QA, "QA", "Qatar", "+974"),
            new(CountryCode.RO, "RO", "Romania", "+40"),
            new(CountryCode.RW, "RW", "Rwanda", "+250"),
            new(CountryCode.WS, "WS", "Samoa", "+685"),
            new(CountryCode.SM, "SM", "San Marino", "+378"),
            new(CountryCode.SA, "SA", "Saudi Arabia", "+966"),
            new(CountryCode.SN, "SN", "Senegal", "+221"),
            new(CountryCode.RS, "RS", "Serbia", "+381"),
            new(CountryCode.SC, "SC", "Seychelles", "+248"),
            new(CountryCode.SL, "SL", "Sierra Leone", "+232"),
            new(CountryCode.SG, "SG", "Singapore", "+65"),
            new(CountryCode.SK, "SK", "Slovakia", "+421"),
            new(CountryCode.SI, "SI", "Slovenia", "+386"),
            new(CountryCode.SB, "SB", "Solomon Islands", "+677"),
            new(CountryCode.ZA, "ZA", "South Africa", "+27"),
            new(CountryCode.GS, "GS", "South Georgia and the South Sandwich Islands", "+500"),
            new(CountryCode.ES, "ES", "Spain", "+34"),
            new(CountryCode.LK, "LK", "Sri Lanka", "+94"),
            new(CountryCode.SD, "SD", "Sudan", "+249"),
            new(CountryCode.SR, "SR", "Suriname", "+597"),
            new(CountryCode.SZ, "SZ", "Swaziland", "+268"),
            new(CountryCode.SE, "SE", "Sweden", "+46"),
            new(CountryCode.CH, "CH", "Switzerland", "+41"),
            new(CountryCode.TJ, "TJ", "Tajikistan", "+992"),
            new(CountryCode.TH, "TH", "Thailand", "+66"),
            new(CountryCode.TG, "TG", "Togo", "+228"),
            new(CountryCode.TK, "TK", "Tokelau", "+690"),
            new(CountryCode.TO, "TO", "Tonga", "+676"),
            new(CountryCode.TT, "TT", "Trinidad and Tobago", "+1 868"),
            new(CountryCode.TN, "TN", "Tunisia", "+216"),
            new(CountryCode.TR, "TR", "Turkey", "+90"),
            new(CountryCode.TM, "TM", "Turkmenistan", "+993"),
            new(CountryCode.TC, "TC", "Turks and Caicos Islands", "+1 649"),
            new(CountryCode.TV, "TV", "Tuvalu", "+688"),
            new(CountryCode.UG, "UG", "Uganda", "+256"),
            new(CountryCode.UA, "UA", "Ukraine", "+380"),
            new(CountryCode.AE, "AE", "United Arab Emirates", "+971"),
            new(CountryCode.GB, "GB", "United Kingdom", "+44"),
            new(CountryCode.US, "US", "United States", "+1"),
            new(CountryCode.UY, "UY", "Uruguay", "+598"),
            new(CountryCode.UZ, "UZ", "Uzbekistan", "+998"),
            new(CountryCode.VU, "VU", "Vanuatu", "+678"),
            new(CountryCode.WF, "WF", "Wallis and Futuna", "+681"),
            new(CountryCode.YE, "YE", "Yemen", "+967"),
            new(CountryCode.ZM, "ZM", "Zambia", "+260"),
            new(CountryCode.ZW, "ZW", "Zimbabwe", "+263"),
            new(CountryCode.AX, "AX", "Åland Islands", "+358"),
            new(CountryCode.AQ, "AQ", "Antarctica", "+672"),
            new(CountryCode.BO, "BO", "Bolivia, Plurinational State of", "+591"),
            new(CountryCode.BN, "BN", "Brunei Darussalam", "+673"),
            new(CountryCode.CC, "CC", "Cocos (Keeling) Islands", "+61"),
            new(CountryCode.CD, "CD", "Congo, The Democratic Republic of the", "+243"),
            new(CountryCode.CI, "CI", "Cote d'Ivoire", "+225"),
            new(CountryCode.FK, "FK", "Falkland Islands (Malvinas)", "+500"),
            new(CountryCode.GG, "GG", "Guernsey", "+44"),
            new(CountryCode.VA, "VA", "Holy See (Vatican City State)", "+379"),
            new(CountryCode.HK, "HK", "Hong Kong", "+852"),
            new(CountryCode.IR, "IR", "Iran, Islamic Republic of", "+98"),
            new(CountryCode.IM, "IM", "Isle of Man", "+44"),
            new(CountryCode.JE, "JE", "Jersey", "+44"),
            new(CountryCode.KP, "KP", "Korea, Democratic People's Republic of", "+850"),
            new(CountryCode.KR, "KR", "Korea, Republic of", "+82"),
            new(CountryCode.LA, "LA", "Lao People's Democratic Republic", "+856"),
            new(CountryCode.LY, "LY", "Libyan Arab Jamahiriya", "+218"),
            new(CountryCode.MO, "MO", "Macao", "+853"),
            new(CountryCode.MK, "MK", "Macedonia, The Former Yugoslav Republic of", "+389"),
            new(CountryCode.FM, "FM", "Micronesia, Federated States of", "+691"),
            new(CountryCode.MD, "MD", "Moldova, Republic of", "+373"),
            new(CountryCode.MZ, "MZ", "Mozambique", "+258"),
            new(CountryCode.PS, "PS", "Palestinian Territory, Occupied", "+970"),
            new(CountryCode.PN, "PN", "Pitcairn", "+872"),
            new(CountryCode.RE, "RE", "Réunion", "+262"),
            new(CountryCode.RU, "RU", "Russia", "+7"),
            new(CountryCode.BL, "BL", "Saint Barthélemy", "+590"),
            new(CountryCode.SH, "SH", "Saint Helena, Ascension and Tristan Da Cunha", "+290"),
            new(CountryCode.KN, "KN", "Saint Kitts and Nevis", "+1 869"),
            new(CountryCode.LC, "LC", "Saint Lucia", "+1 758"),
            new(CountryCode.MF, "MF", "Saint Martin", "+590"),
            new(CountryCode.PM, "PM", "Saint Pierre and Miquelon", "+508"),
            new(CountryCode.VC, "VC", "Saint Vincent and the Grenadines", "+1 784"),
            new(CountryCode.ST, "ST", "Sao Tome and Principe", "+239"),
            new(CountryCode.SO, "SO", "Somalia", "+252"),
            new(CountryCode.SJ, "SJ", "Svalbard and Jan Mayen", "+47"),
            new(CountryCode.SY, "SY", "Syrian Arab Republic", "+963"),
            new(CountryCode.TW, "TW", "Taiwan, Province of China", "+886"),
            new(CountryCode.TZ, "TZ", "Tanzania, United Republic of", "+255"),
            new(CountryCode.TL, "TL", "Timor-Leste", "+670"),
            new(CountryCode.VE, "VE", "Venezuela, Bolivarian Republic of", "+58"),
            new(CountryCode.VN, "VN", "Viet Nam", "+84"),
            new(CountryCode.VG, "VG", "Virgin Islands, British", "+1 284"),
            new(CountryCode.VI, "VI", "Virgin Islands, U.S.", "+1 340")
        };

        All = new ReadOnlyCollection<CountryInfo>(items);
        ByEnum = new ReadOnlyDictionary<CountryCode, CountryInfo>(
            items.ToDictionary(x => x.Id)).ToFrozenDictionary();
        ByCode = new ReadOnlyDictionary<string, CountryInfo>(
            items.ToDictionary(x => x.Code, StringComparer.OrdinalIgnoreCase))
            .ToFrozenDictionary();
    }

    public static bool TryGet(CountryCode id, out CountryInfo country)
        => ByEnum.TryGetValue(id, out country);

    public static bool TryGet(string code, out CountryInfo country)
        => ByCode.TryGetValue(code, out country);

    public static string GetName(CountryCode id)
    {
        TryGet(id, out var country);
        return country?.Name;
    }

    public static string GetDialCode(CountryCode id)  
    {
        TryGet(id, out var country);
        return country?.DialCode;
    }

    public static int GetIndex(CountryCode id) => (int)id;
}