using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using JetBrains.Annotations;

// ReSharper disable InconsistentNaming

namespace JJMasterData.Commons.Util;

public enum CountryCode
{
    AF,
    AL,
    DZ,
    AS,
    AD,
    AO,
    AI,
    AG,
    AR,
    AM,
    AW,
    AU,
    AT,
    AZ,
    BS,
    BH,
    BD,
    BB,
    BY,
    BE,
    BZ,
    BJ,
    BM,
    BT,
    BA,
    BW,
    BR,
    IO,
    BG,
    BF,
    BI,
    KH,
    CM,
    CA,
    CV,
    KY,
    CF,
    TD,
    CL,
    CN,
    CX,
    CO,
    KM,
    CG,
    CK,
    CR,
    HR,
    CU,
    CY,
    CZ,
    DK,
    DJ,
    DM,
    DO,
    EC,
    EG,
    SV,
    GQ,
    ER,
    EE,
    ET,
    FO,
    FJ,
    FI,
    FR,
    GF,
    PF,
    GA,
    GM,
    GE,
    DE,
    GH,
    GI,
    GR,
    GL,
    GD,
    GP,
    GU,
    GT,
    GN,
    GW,
    GY,
    HT,
    HN,
    HU,
    IS,
    IN,
    ID,
    IQ,
    IE,
    IL,
    IT,
    JM,
    JP,
    JO,
    KZ,
    KE,
    KI,
    KW,
    KG,
    LV,
    LB,
    LS,
    LR,
    LI,
    LT,
    LU,
    MG,
    MW,
    MY,
    MV,
    ML,
    MT,
    MH,
    MQ,
    MR,
    MU,
    YT,
    MX,
    MC,
    MN,
    ME,
    MS,
    MA,
    MM,
    NA,
    NR,
    NP,
    NL,
    AN,
    NC,
    NZ,
    NI,
    NE,
    NG,
    NU,
    MP,
    NO,
    OM,
    PK,
    PW,
    PA,
    PG,
    PY,
    PE,
    PH,
    PL,
    PT,
    PR,
    QA,
    RO,
    RW,
    WS,
    SM,
    SA,
    SN,
    RS,
    SC,
    SL,
    SG,
    SK,
    SI,
    SB,
    ZA,
    GS,
    ES,
    LK,
    SD,
    SR,
    SZ,
    SE,
    CH,
    TJ,
    TH,
    TG,
    TK,
    TO,
    TT,
    TN,
    TR,
    TM,
    TC,
    TV,
    UG,
    UA,
    AE,
    GB,
    US,
    UY,
    UZ,
    VU,
    WF,
    YE,
    ZM,
    ZW,
    AX,
    AQ,
    BO,
    BN,
    CC,
    CD,
    CI,
    FK,
    GG,
    VA,
    HK,
    IR,
    IM,
    JE,
    KP,
    KR,
    LA,
    LY,
    MO,
    MK,
    FM,
    MD,
    MZ,
    PS,
    PN,
    RE,
    RU,
    BL,
    SH,
    KN,
    LC,
    MF,
    PM,
    VC,
    ST,
    SO,
    SJ,
    SY,
    TW,
    TZ,
    TL,
    VE,
    VN,
    VG,
    VI
}

public sealed record CountryInfo(CountryCode Id, string CountryCode, string Name, string DialCode);

public static class CountryHelper
{
    public static readonly FrozenSet<CountryInfo> All;
    private static readonly FrozenDictionary<string, CountryInfo> ByCountryCode;
    
    static CountryHelper()
    {
        var items = new List<CountryInfo>
        {
            new(CountryCode.AF, nameof(CountryCode.AF), "Afghanistan", "+93"),
            new(CountryCode.AL, nameof(CountryCode.AL), "Albania", "+355"),
            new(CountryCode.DZ, nameof(CountryCode.DZ), "Algeria", "+213"),
            new(CountryCode.AS, nameof(CountryCode.AS), "AmericanSamoa", "+1 684"),
            new(CountryCode.AD, nameof(CountryCode.AD), "Andorra", "+376"),
            new(CountryCode.AO, nameof(CountryCode.AO), "Angola", "+244"),
            new(CountryCode.AI, nameof(CountryCode.AI), "Anguilla", "+1 264"),
            new(CountryCode.AG, nameof(CountryCode.AG), "Antigua and Barbuda", "+1268"),
            new(CountryCode.AR, nameof(CountryCode.AR), "Argentina", "+54"),
            new(CountryCode.AM, nameof(CountryCode.AM), "Armenia", "+374"),
            new(CountryCode.AW, nameof(CountryCode.AW), "Aruba", "+297"),
            new(CountryCode.AU, nameof(CountryCode.AU), "Australia", "+61"),
            new(CountryCode.AT, nameof(CountryCode.AT), "Austria", "+43"),
            new(CountryCode.AZ, nameof(CountryCode.AZ), "Azerbaijan", "+994"),
            new(CountryCode.BS, nameof(CountryCode.BS), "Bahamas", "+1 242"),
            new(CountryCode.BH, nameof(CountryCode.BH), "Bahrain", "+973"),
            new(CountryCode.BD, nameof(CountryCode.BD), "Bangladesh", "+880"),
            new(CountryCode.BB, nameof(CountryCode.BB), "Barbados", "+1 246"),
            new(CountryCode.BY, nameof(CountryCode.BY), "Belarus", "+375"),
            new(CountryCode.BE, nameof(CountryCode.BE), "Belgium", "+32"),
            new(CountryCode.BZ, nameof(CountryCode.BZ), "Belize", "+501"),
            new(CountryCode.BJ, nameof(CountryCode.BJ), "Benin", "+229"),
            new(CountryCode.BM, nameof(CountryCode.BM), "Bermuda", "+1 441"),
            new(CountryCode.BT, nameof(CountryCode.BT), "Bhutan", "+975"),
            new(CountryCode.BA, nameof(CountryCode.BA), "Bosnia and Herzegovina", "+387"),
            new(CountryCode.BW, nameof(CountryCode.BW), "Botswana", "+267"),
            new(CountryCode.BR, nameof(CountryCode.BR), "Brazil", "+55"),
            new(CountryCode.IO, nameof(CountryCode.IO), "British Indian Ocean Territory", "+246"),
            new(CountryCode.BG, nameof(CountryCode.BG), "Bulgaria", "+359"),
            new(CountryCode.BF, nameof(CountryCode.BF), "Burkina Faso", "+226"),
            new(CountryCode.BI, nameof(CountryCode.BI), "Burundi", "+257"),
            new(CountryCode.KH, nameof(CountryCode.KH), "Cambodia", "+855"),
            new(CountryCode.CM, nameof(CountryCode.CM), "Cameroon", "+237"),
            new(CountryCode.CA, nameof(CountryCode.CA), "Canada", "+1"),
            new(CountryCode.CV, nameof(CountryCode.CV), "Cape Verde", "+238"),
            new(CountryCode.KY, nameof(CountryCode.KY), "Cayman Islands", "+ 345"),
            new(CountryCode.CF, nameof(CountryCode.CF), "Central African Republic", "+236"),
            new(CountryCode.TD, nameof(CountryCode.TD), "Chad", "+235"),
            new(CountryCode.CL, nameof(CountryCode.CL), "Chile", "+56"),
            new(CountryCode.CN, nameof(CountryCode.CN), "China", "+86"),
            new(CountryCode.CX, nameof(CountryCode.CX), "Christmas Island", "+61"),
            new(CountryCode.CO, nameof(CountryCode.CO), "Colombia", "+57"),
            new(CountryCode.KM, nameof(CountryCode.KM), "Comoros", "+269"),
            new(CountryCode.CG, nameof(CountryCode.CG), "Congo", "+242"),
            new(CountryCode.CK, nameof(CountryCode.CK), "Cook Islands", "+682"),
            new(CountryCode.CR, nameof(CountryCode.CR), "Costa Rica", "+506"),
            new(CountryCode.HR, nameof(CountryCode.HR), "Croatia", "+385"),
            new(CountryCode.CU, nameof(CountryCode.CU), "Cuba", "+53"),
            new(CountryCode.CY, nameof(CountryCode.CY), "Cyprus", "+537"),
            new(CountryCode.CZ, nameof(CountryCode.CZ), "Czech Republic", "+420"),
            new(CountryCode.DK, nameof(CountryCode.DK), "Denmark", "+45"),
            new(CountryCode.DJ, nameof(CountryCode.DJ), "Djibouti", "+253"),
            new(CountryCode.DM, nameof(CountryCode.DM), "Dominica", "+1 767"),
            new(CountryCode.DO, nameof(CountryCode.DO), "Dominican Republic", "+1 849"),
            new(CountryCode.EC, nameof(CountryCode.EC), "Ecuador", "+593"),
            new(CountryCode.EG, nameof(CountryCode.EG), "Egypt", "+20"),
            new(CountryCode.SV, nameof(CountryCode.SV), "El Salvador", "+503"),
            new(CountryCode.GQ, nameof(CountryCode.GQ), "Equatorial Guinea", "+240"),
            new(CountryCode.ER, nameof(CountryCode.ER), "Eritrea", "+291"),
            new(CountryCode.EE, nameof(CountryCode.EE), "Estonia", "+372"),
            new(CountryCode.ET, nameof(CountryCode.ET), "Ethiopia", "+251"),
            new(CountryCode.FO, nameof(CountryCode.FO), "Faroe Islands", "+298"),
            new(CountryCode.FJ, nameof(CountryCode.FJ), "Fiji", "+679"),
            new(CountryCode.FI, nameof(CountryCode.FI), "Finland", "+358"),
            new(CountryCode.FR, nameof(CountryCode.FR), "France", "+33"),
            new(CountryCode.GF, nameof(CountryCode.GF), "French Guiana", "+594"),
            new(CountryCode.PF, nameof(CountryCode.PF), "French Polynesia", "+689"),
            new(CountryCode.GA, nameof(CountryCode.GA), "Gabon", "+241"),
            new(CountryCode.GM, nameof(CountryCode.GM), "Gambia", "+220"),
            new(CountryCode.GE, nameof(CountryCode.GE), "Georgia", "+995"),
            new(CountryCode.DE, nameof(CountryCode.DE), "Germany", "+49"),
            new(CountryCode.GH, nameof(CountryCode.GH), "Ghana", "+233"),
            new(CountryCode.GI, nameof(CountryCode.GI), "Gibraltar", "+350"),
            new(CountryCode.GR, nameof(CountryCode.GR), "Greece", "+30"),
            new(CountryCode.GL, nameof(CountryCode.GL), "Greenland", "+299"),
            new(CountryCode.GD, nameof(CountryCode.GD), "Grenada", "+1 473"),
            new(CountryCode.GP, nameof(CountryCode.GP), "Guadeloupe", "+590"),
            new(CountryCode.GU, nameof(CountryCode.GU), "Guam", "+1 671"),
            new(CountryCode.GT, nameof(CountryCode.GT), "Guatemala", "+502"),
            new(CountryCode.GN, nameof(CountryCode.GN), "Guinea", "+224"),
            new(CountryCode.GW, nameof(CountryCode.GW), "Guinea-Bissau", "+245"),
            new(CountryCode.GY, nameof(CountryCode.GY), "Guyana", "+595"),
            new(CountryCode.HT, nameof(CountryCode.HT), "Haiti", "+509"),
            new(CountryCode.HN, nameof(CountryCode.HN), "Honduras", "+504"),
            new(CountryCode.HU, nameof(CountryCode.HU), "Hungary", "+36"),
            new(CountryCode.IS, nameof(CountryCode.IS), "Iceland", "+354"),
            new(CountryCode.IN, nameof(CountryCode.IN), "India", "+91"),
            new(CountryCode.ID, nameof(CountryCode.ID), "Indonesia", "+62"),
            new(CountryCode.IQ, nameof(CountryCode.IQ), "Iraq", "+964"),
            new(CountryCode.IE, nameof(CountryCode.IE), "Ireland", "+353"),
            new(CountryCode.IL, nameof(CountryCode.IL), "Israel", "+972"),
            new(CountryCode.IT, nameof(CountryCode.IT), "Italy", "+39"),
            new(CountryCode.JM, nameof(CountryCode.JM), "Jamaica", "+1 876"),
            new(CountryCode.JP, nameof(CountryCode.JP), "Japan", "+81"),
            new(CountryCode.JO, nameof(CountryCode.JO), "Jordan", "+962"),
            new(CountryCode.KZ, nameof(CountryCode.KZ), "Kazakhstan", "+7 7"),
            new(CountryCode.KE, nameof(CountryCode.KE), "Kenya", "+254"),
            new(CountryCode.KI, nameof(CountryCode.KI), "Kiribati", "+686"),
            new(CountryCode.KW, nameof(CountryCode.KW), "Kuwait", "+965"),
            new(CountryCode.KG, nameof(CountryCode.KG), "Kyrgyzstan", "+996"),
            new(CountryCode.LV, nameof(CountryCode.LV), "Latvia", "+371"),
            new(CountryCode.LB, nameof(CountryCode.LB), "Lebanon", "+961"),
            new(CountryCode.LS, nameof(CountryCode.LS), "Lesotho", "+266"),
            new(CountryCode.LR, nameof(CountryCode.LR), "Liberia", "+231"),
            new(CountryCode.LI, nameof(CountryCode.LI), "Liechtenstein", "+423"),
            new(CountryCode.LT, nameof(CountryCode.LT), "Lithuania", "+370"),
            new(CountryCode.LU, nameof(CountryCode.LU), "Luxembourg", "+352"),
            new(CountryCode.MG, nameof(CountryCode.MG), "Madagascar", "+261"),
            new(CountryCode.MW, nameof(CountryCode.MW), "Malawi", "+265"),
            new(CountryCode.MY, nameof(CountryCode.MY), "Malaysia", "+60"),
            new(CountryCode.MV, nameof(CountryCode.MV), "Maldives", "+960"),
            new(CountryCode.ML, nameof(CountryCode.ML), "Mali", "+223"),
            new(CountryCode.MT, nameof(CountryCode.MT), "Malta", "+356"),
            new(CountryCode.MH, nameof(CountryCode.MH), "Marshall Islands", "+692"),
            new(CountryCode.MQ, nameof(CountryCode.MQ), "Martinique", "+596"),
            new(CountryCode.MR, nameof(CountryCode.MR), "Mauritania", "+222"),
            new(CountryCode.MU, nameof(CountryCode.MU), "Mauritius", "+230"),
            new(CountryCode.YT, nameof(CountryCode.YT), "Mayotte", "+262"),
            new(CountryCode.MX, nameof(CountryCode.MX), "Mexico", "+52"),
            new(CountryCode.MC, nameof(CountryCode.MC), "Monaco", "+377"),
            new(CountryCode.MN, nameof(CountryCode.MN), "Mongolia", "+976"),
            new(CountryCode.ME, nameof(CountryCode.ME), "Montenegro", "+382"),
            new(CountryCode.MS, nameof(CountryCode.MS), "Montserrat", "+1664"),
            new(CountryCode.MA, nameof(CountryCode.MA), "Morocco", "+212"),
            new(CountryCode.MM, nameof(CountryCode.MM), "Myanmar", "+95"),
            new(CountryCode.NA, nameof(CountryCode.NA), "Namibia", "+264"),
            new(CountryCode.NR, nameof(CountryCode.NR), "Nauru", "+674"),
            new(CountryCode.NP, nameof(CountryCode.NP), "Nepal", "+977"),
            new(CountryCode.NL, nameof(CountryCode.NL), "Netherlands", "+31"),
            new(CountryCode.AN, nameof(CountryCode.AN), "Netherlands Antilles", "+599"),
            new(CountryCode.NC, nameof(CountryCode.NC), "New Caledonia", "+687"),
            new(CountryCode.NZ, nameof(CountryCode.NZ), "New Zealand", "+64"),
            new(CountryCode.NI, nameof(CountryCode.NI), "Nicaragua", "+505"),
            new(CountryCode.NE, nameof(CountryCode.NE), "Niger", "+227"),
            new(CountryCode.NG, nameof(CountryCode.NG), "Nigeria", "+234"),
            new(CountryCode.NU, nameof(CountryCode.NU), "Niue", "+683"),
            new(CountryCode.MP, nameof(CountryCode.MP), "Northern Mariana Islands", "+1 670"),
            new(CountryCode.NO, nameof(CountryCode.NO), "Norway", "+47"),
            new(CountryCode.OM, nameof(CountryCode.OM), "Oman", "+968"),
            new(CountryCode.PK, nameof(CountryCode.PK), "Pakistan", "+92"),
            new(CountryCode.PW, nameof(CountryCode.PW), "Palau", "+680"),
            new(CountryCode.PA, nameof(CountryCode.PA), "Panama", "+507"),
            new(CountryCode.PG, nameof(CountryCode.PG), "Papua New Guinea", "+675"),
            new(CountryCode.PY, nameof(CountryCode.PY), "Paraguay", "+595"),
            new(CountryCode.PE, nameof(CountryCode.PE), "Peru", "+51"),
            new(CountryCode.PH, nameof(CountryCode.PH), "Philippines", "+63"),
            new(CountryCode.PL, nameof(CountryCode.PL), "Poland", "+48"),
            new(CountryCode.PT, nameof(CountryCode.PT), "Portugal", "+351"),
            new(CountryCode.PR, nameof(CountryCode.PR), "Puerto Rico", "+1 939"),
            new(CountryCode.QA, nameof(CountryCode.QA), "Qatar", "+974"),
            new(CountryCode.RO, nameof(CountryCode.RO), "Romania", "+40"),
            new(CountryCode.RW, nameof(CountryCode.RW), "Rwanda", "+250"),
            new(CountryCode.WS, nameof(CountryCode.WS), "Samoa", "+685"),
            new(CountryCode.SM, nameof(CountryCode.SM), "San Marino", "+378"),
            new(CountryCode.SA, nameof(CountryCode.SA), "Saudi Arabia", "+966"),
            new(CountryCode.SN, nameof(CountryCode.SN), "Senegal", "+221"),
            new(CountryCode.RS, nameof(CountryCode.RS), "Serbia", "+381"),
            new(CountryCode.SC, nameof(CountryCode.SC), "Seychelles", "+248"),
            new(CountryCode.SL, nameof(CountryCode.SL), "Sierra Leone", "+232"),
            new(CountryCode.SG, nameof(CountryCode.SG), "Singapore", "+65"),
            new(CountryCode.SK, nameof(CountryCode.SK), "Slovakia", "+421"),
            new(CountryCode.SI, nameof(CountryCode.SI), "Slovenia", "+386"),
            new(CountryCode.SB, nameof(CountryCode.SB), "Solomon Islands", "+677"),
            new(CountryCode.ZA, nameof(CountryCode.ZA), "South Africa", "+27"),
            new(CountryCode.GS, nameof(CountryCode.GS), "South Georgia and the South Sandwich Islands", "+500"),
            new(CountryCode.ES, nameof(CountryCode.ES), "Spain", "+34"),
            new(CountryCode.LK, nameof(CountryCode.LK), "Sri Lanka", "+94"),
            new(CountryCode.SD, nameof(CountryCode.SD), "Sudan", "+249"),
            new(CountryCode.SR, nameof(CountryCode.SR), "Suriname", "+597"),
            new(CountryCode.SZ, nameof(CountryCode.SZ), "Swaziland", "+268"),
            new(CountryCode.SE, nameof(CountryCode.SE), "Sweden", "+46"),
            new(CountryCode.CH, nameof(CountryCode.CH), "Switzerland", "+41"),
            new(CountryCode.TJ, nameof(CountryCode.TJ), "Tajikistan", "+992"),
            new(CountryCode.TH, nameof(CountryCode.TH), "Thailand", "+66"),
            new(CountryCode.TG, nameof(CountryCode.TG), "Togo", "+228"),
            new(CountryCode.TK, nameof(CountryCode.TK), "Tokelau", "+690"),
            new(CountryCode.TO, nameof(CountryCode.TO), "Tonga", "+676"),
            new(CountryCode.TT, nameof(CountryCode.TT), "Trinidad and Tobago", "+1 868"),
            new(CountryCode.TN, nameof(CountryCode.TN), "Tunisia", "+216"),
            new(CountryCode.TR, nameof(CountryCode.TR), "Turkey", "+90"),
            new(CountryCode.TM, nameof(CountryCode.TM), "Turkmenistan", "+993"),
            new(CountryCode.TC, nameof(CountryCode.TC), "Turks and Caicos Islands", "+1 649"),
            new(CountryCode.TV, nameof(CountryCode.TV), "Tuvalu", "+688"),
            new(CountryCode.UG, nameof(CountryCode.UG), "Uganda", "+256"),
            new(CountryCode.UA, nameof(CountryCode.UA), "Ukraine", "+380"),
            new(CountryCode.AE, nameof(CountryCode.AE), "United Arab Emirates", "+971"),
            new(CountryCode.GB, nameof(CountryCode.GB), "United Kingdom", "+44"),
            new(CountryCode.US, nameof(CountryCode.US), "United States", "+1"),
            new(CountryCode.UY, nameof(CountryCode.UY), "Uruguay", "+598"),
            new(CountryCode.UZ, nameof(CountryCode.UZ), "Uzbekistan", "+998"),
            new(CountryCode.VU, nameof(CountryCode.VU), "Vanuatu", "+678"),
            new(CountryCode.WF, nameof(CountryCode.WF), "Wallis and Futuna", "+681"),
            new(CountryCode.YE, nameof(CountryCode.YE), "Yemen", "+967"),
            new(CountryCode.ZM, nameof(CountryCode.ZM), "Zambia", "+260"),
            new(CountryCode.ZW, nameof(CountryCode.ZW), "Zimbabwe", "+263"),
            new(CountryCode.AX, nameof(CountryCode.AX), "Åland Islands", "+358"),
            new(CountryCode.AQ, nameof(CountryCode.AQ), "Antarctica", "+672"),
            new(CountryCode.BO, nameof(CountryCode.BO), "Bolivia, Plurinational State of", "+591"),
            new(CountryCode.BN, nameof(CountryCode.BN), "Brunei Darussalam", "+673"),
            new(CountryCode.CC, nameof(CountryCode.CC), "Cocos (Keeling) Islands", "+61"),
            new(CountryCode.CD, nameof(CountryCode.CD), "Congo, The Democratic Republic of the", "+243"),
            new(CountryCode.CI, nameof(CountryCode.CI), "Cote d'Ivoire", "+225"),
            new(CountryCode.FK, nameof(CountryCode.FK), "Falkland Islands (Malvinas)", "+500"),
            new(CountryCode.GG, nameof(CountryCode.GG), "Guernsey", "+44"),
            new(CountryCode.VA, nameof(CountryCode.VA), "Holy See (Vatican City State)", "+379"),
            new(CountryCode.HK, nameof(CountryCode.HK), "Hong Kong", "+852"),
            new(CountryCode.IR, nameof(CountryCode.IR), "Iran, Islamic Republic of", "+98"),
            new(CountryCode.IM, nameof(CountryCode.IM), "Isle of Man", "+44"),
            new(CountryCode.JE, nameof(CountryCode.JE), "Jersey", "+44"),
            new(CountryCode.KP, nameof(CountryCode.KP), "Korea, Democratic People's Republic of", "+850"),
            new(CountryCode.KR, nameof(CountryCode.KR), "Korea, Republic of", "+82"),
            new(CountryCode.LA, nameof(CountryCode.LA), "Lao People's Democratic Republic", "+856"),
            new(CountryCode.LY, nameof(CountryCode.LY), "Libyan Arab Jamahiriya", "+218"),
            new(CountryCode.MO, nameof(CountryCode.MO), "Macao", "+853"),
            new(CountryCode.MK, nameof(CountryCode.MK), "Macedonia, The Former Yugoslav Republic of", "+389"),
            new(CountryCode.FM, nameof(CountryCode.FM), "Micronesia, Federated States of", "+691"),
            new(CountryCode.MD, nameof(CountryCode.MD), "Moldova, Republic of", "+373"),
            new(CountryCode.MZ, nameof(CountryCode.MZ), "Mozambique", "+258"),
            new(CountryCode.PS, nameof(CountryCode.PS), "Palestinian Territory, Occupied", "+970"),
            new(CountryCode.PN, nameof(CountryCode.PN), "Pitcairn", "+872"),
            new(CountryCode.RE, nameof(CountryCode.RE), "Réunion", "+262"),
            new(CountryCode.RU, nameof(CountryCode.RU), "Russia", "+7"),
            new(CountryCode.BL, nameof(CountryCode.BL), "Saint Barthélemy", "+590"),
            new(CountryCode.SH, nameof(CountryCode.SH), "Saint Helena, Ascension and Tristan Da Cunha", "+290"),
            new(CountryCode.KN, nameof(CountryCode.KN), "Saint Kitts and Nevis", "+1 869"),
            new(CountryCode.LC, nameof(CountryCode.LC), "Saint Lucia", "+1 758"),
            new(CountryCode.MF, nameof(CountryCode.MF), "Saint Martin", "+590"),
            new(CountryCode.PM, nameof(CountryCode.PM), "Saint Pierre and Miquelon", "+508"),
            new(CountryCode.VC, nameof(CountryCode.VC), "Saint Vincent and the Grenadines", "+1 784"),
            new(CountryCode.ST, nameof(CountryCode.ST), "Sao Tome and Principe", "+239"),
            new(CountryCode.SO, nameof(CountryCode.SO), "Somalia", "+252"),
            new(CountryCode.SJ, nameof(CountryCode.SJ), "Svalbard and Jan Mayen", "+47"),
            new(CountryCode.SY, nameof(CountryCode.SY), "Syrian Arab Republic", "+963"),
            new(CountryCode.TW, nameof(CountryCode.TW), "Taiwan, Province of China", "+886"),
            new(CountryCode.TZ, nameof(CountryCode.TZ), "Tanzania, United Republic of", "+255"),
            new(CountryCode.TL, nameof(CountryCode.TL), "Timor-Leste", "+670"),
            new(CountryCode.VE, nameof(CountryCode.VE), "Venezuela, Bolivarian Republic of", "+58"),
            new(CountryCode.VN, nameof(CountryCode.VN), "Viet Nam", "+84"),
            new(CountryCode.VG, nameof(CountryCode.VG), "Virgin Islands, British", "+1 284"),
            new(CountryCode.VI, nameof(CountryCode.VI), "Virgin Islands, U.S.", "+1 340")
        };
        
        All = items.ToFrozenSet();
        ByCountryCode = items.ToFrozenDictionary(x => x.CountryCode, StringComparer.InvariantCultureIgnoreCase);
    }
    
    public static bool TryGet(string countryCode, [CanBeNull] out CountryInfo country)
    {
        return ByCountryCode.TryGetValue(countryCode, out country);
    }
}
