# This is a basic workflow to help you get started with Actions

name: Docs

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Publish DocFX website
        run: |
               cd .\doc\JJMasterData.Documentation
               docfx metadata
               cd plugins/nested_namespaces
               npm install
               node nested_namespaces.js
               cd..
               cd..
               docfx build
               xcopy .\_site C:\WebSites\JJ\JJDoc /s /e /y

