

name: Docs

on:
  workflow_dispatch:

jobs:
  docfx:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Publish DocFX website
        run: |
               cd doc\Documentation
               docfx metadata
               docfx build
               xcopy .\_site C:\WebSites\JJ\JJSiteInstitucional\docs\JJMasterData /s /e /y
