name: .NET

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Setup NodeJS
      uses: actions/setup-node@v4

    - name: Restore TypeScript dependencies
      run: |
          cd src/Web
          npm install
          cd ../../..
          
    - name: Build
      run: dotnet build
