name: .NET

on:
  push:
    branches: [ "main", "rc" ]
  pull_request:
    branches: [ "main", "rc" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
        
    - name: Build
      run: |
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          VERSION_SUFFIX="rc.${{ github.event.pull_request.number }}.${{ github.run_number }}"
        else
          VERSION_SUFFIX=""
        fi
        dotnet build -p:VersionSuffix="${VERSION_SUFFIX}" -p:ContinuousIntegrationBuild=true
