name: NuGet Publish

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
        
      - name: Setup NodeJS
        uses: actions/setup-node@v3.4.1

      - name: Restore NuGet packages
        run: |
          dotnet restore
        
      - name: Install NPM dependencies
        run: |
          npm i --prefix src/JJMasterData.Web

  nuget-push:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        project:
          - src/JJMasterData.Commons
          - src/JJMasterData.Core
          - src/JJMasterData.Web
          - src/Plugins/JJMasterData.Hangfire
          - src/Plugins/JJMasterData.Pdf

    steps:
      - uses: actions/checkout@v2

      - name: Build and pack NuGet package
        run: |
          dotnet build -c release
          dotnet pack -c release --output="nuget"
          cd nuget
  
      - name: Publish NuGet package
        run: |
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
