name: NuGet Publish

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
    
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.101
        
      - name: Setup NodeJS
        uses: actions/setup-node@v4

      - name: Restore NuGet packages
        run: |
          dotnet restore
    
  nuget-push:
    runs-on: windows-latest
    needs: setup
    strategy:
      matrix:
        project:
          - src/Commons
          - src/Core
          - src/Web
          - src/WebApi
          - src/Plugins/Hangfire
          - src/Plugins/Pdf
    steps:
      - uses: actions/checkout@v4
      - name: Build and publish NuGet package
        shell: pwsh
        run: |
          npm install --prefix src/Web
          Push-Location ${{ matrix.project }}
          dotnet build -c release
          dotnet pack -c release --output="nuget"
          Push-Location nuget
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
          Pop-Location
          Pop-Location
