name: NuGet Publish

on:
  workflow_dispatch:

jobs:
  nuget-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        
      - name: Setup NodeJS
        uses: actions/setup-node@v3.4.1

      - name: NuGet Publish
        run: |
          cd src/JJMasterData.Commons
          dotnet build -c release
          dotnet pack -c release --output="nuget"
          cd nuget
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
          cd ../../..
          cd src/JJMasterData.Core
          dotnet build -c release
          dotnet pack -c release --output="nuget"
          cd nuget
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
          cd ../../..
          cd src/JJMasterData.Web
          npm install
          dotnet build -c release
          dotnet pack -c release --output="nuget"
          cd nuget
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
